extends Node

const DEFAULT_PLAYER_MASS = 2
const PUP_PLAYER_MASS = 0.8

const DEFAULT_PLAYER_SCALE = 1
const PUP_PLAYER_SCALE = 1.5


# PowerUPs
enum PUP {SPEED=0, SIZE=1}

# enum PUP {SPEED, SIZE, GOAL_SWAP}
